// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddOwnerFunctionalTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addOwnerFunctional() {
    driver.get("http://localhost:8081/");
    driver.manage().window().setSize(new Dimension(1920, 982));
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) span:nth-child(2)")).click();
    driver.findElement(By.linkText("Add Owner")).click();
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.id("firstName")).sendKeys("Jim");
    driver.findElement(By.id("lastName")).sendKeys("Cju");
    driver.findElement(By.id("address")).sendKeys("625 ");
    driver.findElement(By.id("address")).sendKeys("625 Cardinal");
    driver.findElement(By.id("address")).sendKeys("625 Cardinal Ave");
    driver.findElement(By.id("city")).sendKeys("Sun");
    driver.findElement(By.id("city")).sendKeys("Sun Praire");
    driver.findElement(By.id("telephone")).click();
    driver.findElement(By.id("telephone")).click();
    driver.findElement(By.id("telephone")).click();
    driver.findElement(By.id("telephone")).sendKeys("6085551029");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("success-message")).click();
    assertThat(driver.findElement(By.cssSelector("#success-message > span")).getText(), is("New Owner Created"));
  }
}
